### ISSUE TITLE
老哥问个问题

### ISSUE THREAD

**Issue by buzai** [brobwind/pie-device-brobwind-rpi3#1]
我在你的博客上注册不了，没法设置密码。我想在 树莓派上 通过 uboot 启动 kindle 的系统技术上可以实现么，我看你的博客是跟我这个想法反的你是在kindle上跑别的系统

**Comment by brobwind** [comment]
哦，我试了一下，确实有些问题。多谢
是的，我本来是打算在kindle上跑Android系统的，无耐kindle的内存太小，无法达到要求，只好放弃。

如果你想在树莓派跑kindle系统，估计可行吧，kernel用树莓派的，userspace的所有二进制用kindle的。
关于显示部分，如果kindle上层app是通过framebuffer直接操作的，那么就比较好办，看kindle的framebuffer在哪个位置，然后再看看树莓派的framebuffer在哪个位置，如果两个位置不一样，就创建个软连接。
输入方面的，可能需要修改kernel input 相关的代码。
wifi: 可能比较麻烦，可能需要自己重编wpa_supplicant.

**Comment by buzai** [comment]
@brobwind 🙏多谢
