### ISSUE TITLE
Required space?

### ISSUE THREAD

**Issue by joeczar** [brobwind/pie-device-brobwind-rpi3#5]
Hi,

I've tried this twice now and both times ran out of space on the partition i was planning on building it on, first time 20gb, second 50gb. Is this normal? Any idea what is required? Am I making a mistake somewhere?

Thanks.

**Comment by brobwind** [comment]
It requires about 130GB with source code and about 60GB for out folder.

**Comment by ricklau** [comment]
My sync was 73GB for code only.
